services:
  backend:
    image: docker.io/qqlx/go-web:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      - CONFIG_PATH=/app/config.yaml
      - CASBIN_MODE_PATH=/app/model.conf
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./model.conf:/app/model.conf
